export const SCOOTER_SELECCT = 'SCOOTER_SELECCT';
export const SCOOTER_SELECCT_MORE = 'SCOOTER_SELECCT_MORE';


export const FETCH_SUCCEEDED = 'FETCH_SUCCEEDED';
export const FETCH_FAILED = 'FETCH_FAILED';
export const FETCH_SUCCEEDED_MORE = 'FETCH_SUCCEEDED_MORE';