const HOME = "HOME";
const SCOOTER = "SCOOTER";
const HOMEDETAIL = "HOMEDETAIL";

const NOTICEBOARD = "NOTICEBOARD";
const NOTICEBOARDDETAIL = "NOTICEBOARDDETAIL";

const SEARCH = "SEARCH";
const SEARCHDETAIL = "SEARCHDETAIL";

const HOTCALL = "HOTCALL";
const MORE = "MORE";


export { HOME, HOTCALL, MORE, NOTICEBOARD, SEARCH, SCOOTER, HOMEDETAIL, NOTICEBOARDDETAIL, SEARCHDETAIL};