const HOME = "HOME";
const HOTCALL = "HOTCALL";
const MORE = "MORE";
const NOTICEBOARD = "NOTICEBOARD";
const NOTICEBOARDDETAIL = "NOTICEBOARDDETAIL";
const SEARCH = "SEARCH";
const SCOOTER = "SCOOTER";
const HOMEDETAIL = "HOMEDETAIL";


export { HOME, HOTCALL, MORE, NOTICEBOARD, SEARCH, SCOOTER, HOMEDETAIL, NOTICEBOARDDETAIL};