const HOME = "HOME";
const HOTCALL = "HOTCALL";
const MORE = "MORE";
const NOTICEBOARD = "NOTICEBOARD";
const SEARCH = "SEARCH";
const SCOOTER = "SCOOTER";

export { HOME, HOTCALL, MORE, NOTICEBOARD, SEARCH, SCOOTER };